//
//  PodcastPresenter.swift
//  Podcast
//
//  Created by Burak Donat on 5.11.2020.
//  Copyright (c) 2020 Burak Donat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PodcastAPI

protocol PodcastPresentationLogic{
  func presentPodcasts(response: Podcast.FetchPodcasts.Response)
}

class PodcastPresenter: PodcastPresentationLogic {
    
  weak var viewController: PodcastDisplayLogic?
  
  // MARK: Present Podcasts
  
  func presentPodcasts(response: Podcast.FetchPodcasts.Response) {
    var displayedPodcasts: [Podcast.FetchPodcasts.ViewModel.DisplayedPodcast] = []
    
    for podcast in response.podcasts.results {
        let displayedPodcast = Podcast.FetchPodcasts.ViewModel.DisplayedPodcast(artistName: podcast.artistName, name: podcast.name, artworkUrl100: podcast.artworkUrl100)
        displayedPodcasts.append(displayedPodcast)
        
    }
    let viewModel = Podcast.FetchPodcasts.ViewModel(displayedPocasts: displayedPodcasts)
    viewController?.displayPodcasts(viewModel: viewModel)
    
  }
}
