//
//  PodcastInteractor.swift
//  Podcast
//
//  Created by Burak Donat on 5.11.2020.
//  Copyright (c) 2020 Burak Donat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PodcastAPI

protocol PodcastBusinessLogic {
    func fetchPodcasts(request: Podcast.FetchPodcasts.Request)
}

protocol PodcastDataStore {
    var podcasts: [PodcastModel]? { get }
}

class PodcastInteractor: PodcastBusinessLogic, PodcastDataStore {
    
    var podcasts: [PodcastModel]?
    
    var presenter: PodcastPresentationLogic?
    var worker = PodcastWorker(api: API())
    
    // MARK: Fetch Podcasts
    
    func fetchPodcasts(request: Podcast.FetchPodcasts.Request) {
        worker.fetchPodcasts({ [weak self] (podcasts) in
            guard let self = self else { return }
            
            self.podcasts = podcasts.results
            let response = Podcast.FetchPodcasts.Response(podcasts: podcasts)
            self.presenter?.presentPodcasts(response: response)
        })
    }
}
