//
//  PodcastModels.swift
//  Podcast
//
//  Created by Burak Donat on 5.11.2020.
//  Copyright (c) 2020 Burak Donat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PodcastAPI

enum Podcast
{
    // MARK: Use cases
    
    enum FetchPodcasts
    {
        struct Request {
        }
        
        struct Response {
            var podcasts: PodcastResponse
        }
        
        struct ViewModel {
            
            struct DisplayedPodcast {
                var artistName: String
                var name: String
                var artworkUrl100: String
            }
            
            var displayedPocasts: [DisplayedPodcast]
        }
    }
}
