//
//  PodcastWorker.swift
//  Podcast
//
//  Created by Burak Donat on 5.11.2020.
//  Copyright (c) 2020 Burak Donat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PodcastAPI

class PodcastWorker {
    
    private let api: API
    
    init(api: API) {
        self.api = api
    }

    func fetchPodcasts(_ completion: @escaping (PodcastResponse) -> Void) {
        self.api.getPodcasts { (result) in
            switch result {
            case .success(let podcast):
                completion(podcast)
            case .failure(let error):
                print(error)
            }
        }
    }
}
